### ISSUE TITLE
Code selection overlaps with chapter text on mobile

### ISSUE THREAD

**Issue by julianschacher** [algorithm-archivists/algorithm-archive#102]
The code selection overlaps with the text of the current chapter on mobile.

**iOS - Safari - iPhone SE:**
![img_4957_screenshot_aaa_codeselection_and_text_overlapping_ios_safari_iphone_se](https://user-images.githubusercontent.com/26492670/39556464-c295c4ca-4e80-11e8-9379-854da01edeb8.png)

**Firefox - Samsung Galaxy S7 - Mac:**
![screen shot 2018-05-03 at 03 13 24_screenshot_aaa_codeselection_and_text_overlapping_ff_samsung_galaxy_s7_mac](https://user-images.githubusercontent.com/26492670/39556466-c66cb4d2-4e80-11e8-938a-b32504b0e702.png)

**Comment by Butt4cak3** [comment]
Tested on actual Android running hardware just in case and got the same thing.

**Comment by Butt4cak3** [comment]
I looked into this and it doesn't look like there's a simple CSS-only fix for this.

**Comment by leios** [comment]
Yeah, I was looking it up yesterday and couldn't fine a solution either. I think the problem is in the implementation of the theme-api, right? Why is it different for mobile?

**Comment by julianschacherpp** [comment]
It seems like the theme-api doesn't have enough space to put the languages in the top row that still covers the text by providing a white background. Then the theme-api has to put the other options below that row and then they overlap with the text.

**Comment by MichalHanajik** [comment]
See #315

**Comment by julianschacher** [comment]
Since #315 is merged now, this issue is resolved. Big thanks to @MichalHanajik .
