### ISSUE TITLE
Complexity notation page inconsistent with array indexing

### ISSUE THREAD

**Issue by chrisb2244** [algorithm-archivists/algorithm-archive#123]
Some parts of the complexity notation page (chapters/principles_of_code/notation/notation.md) list arrays with base 0 indexing, others use things like `a[1]` to refer to the first element.

Although it's possible they could be from different languages, the examples are less likely to be misleading if all arrays are 0 based.

The linear time example also lists i = 0 : length, which would probably lead to an out of bounds error in languages providing them (not sure if this includes Julia) or runtime exception/similar.

**Comment by Gathros** [comment]
The examples in that chapter is in Julia which have arrays starting from 1 not 0, which should have been stated @leios. But `for i = 0:length(a)` is a mistake it should be `for i = 1:length(a)`. Thanks.

**Comment by Butt4cak3** [comment]
This has been fixed in #122
