### ISSUE TITLE
extra term in FFT

### ISSUE THREAD

**Issue by earthfail** [algorithm-archivists/algorithm-archive#129]
hello @leios , I have been reading [FFT](https://www.algorithm-archive.org/chapters/FFT/cooley_tukey.html#) and the step where using e2πiθ=cos(2πθ)+isin(2πθ) (line 41)
to change f(x)=∫∞−∞F(ξ)e2πiξxdξ (line 19)
to f(x)=∫∞−∞F(ξ)(cos(2πξx)+isin(2πξx))e2πiξxdξ (line 49)

seems off, especially the extra e2πiξx at the end (line 49)

**Comment by Gathros** [comment]
I think it's a typo the maths does not make sense.

**Comment by Butt4cak3** [comment]
For future reference, this has been fixed in c8e6717b8cbfefe9add1deeb62e80bd07bf872fb.

**Comment by earthfail** [comment]
btw I see that some PR are merged but the effect doesn't show on the website for example
the monte carlo implementation in haskell

**Comment by Gathros** [comment]
@leios needs to update the site repo.
