### ISSUE TITLE
Error in Tree Traversal code c#

### ISSUE THREAD

**Issue by xam4lor** [algorithm-archivists/algorithm-archive#134]
The function DFSStack() for the Tree Traversal's example is missing a parameter of type "Node" called "root".

**Comment by julianschacher** [comment]
I'll look into it and come back to you! :)

**Comment by julianschacher** [comment]
You're right. Currently the `root` gets set by the constructor, which will just make up a "fake" Tree.
Making the methods accessible from the outside and really use the algorithm is a good idea actually. We should probably switch the algorithm over to do so.

**Comment by xam4lor** [comment]
I think so ! It's not very clear, the way it's made right now !

**Comment by julianschacher** [comment]
Yeah it's definitely a flaw! I'll go ahead and change it. Or do you want to (I don't want to take away your issue)?

**Comment by xam4lor** [comment]
Let's go do it by myself ;)

**Comment by julianschacher** [comment]
Yes, but I currently have a PR changing TreeTraversal open. Since you know C#, would you mind to review it and work on the new master? Otherwise you can of course just work on the current master and I update my PR. (PR: https://github.com/algorithm-archivists/algorithm-archive/pull/120)

**Comment by xam4lor** [comment]
I'm sorry but I don't really know how to do that :/
