### ISSUE TITLE
Style Guide for Haskell

### ISSUE THREAD

**Issue by lulucca12** [algorithm-archivists/algorithm-archive#152]
**Style Guide for Haskell**
There are some style considerations to make in regret to writing Haskell code.

**Paradigm Preference**
  Normally Haskell programmers prefer to write declarative code instead of imperative code, but as imperative code is used on the mainstream and most non-haskell coders are more familiar with it, it could be viewed as an alternative.

**Code Readability** 
  As said in the "how_to_contribute.md" file we should use the style preferences of the language we are writing, but we should also consider readability as a must, because our code is going to be public and accessible on the internet.
  I would recommend writing code as readable as possible even if you would rewrite it in a not so familiar style of coding.

An example:

```haskell
euclidSub :: Integer -> Integer -> Integer
euclidSub a b = inner (abs a) (abs b) where
  inner a b =
    if a == b then
      a
    else if a < b then
      euclidSub a (b - a)
    else
      euclidSub (a - b) b
```
Could Be wiritten as:

```haskell
euclidSub :: Integer -> Integer -> Integer
euclidSub a b = inner (abs a) (abs b)
  where
    inner a b
      | a == b = a
      | a < b = euclidSub a (b - a)
      | otherwise = euclidSub (a - b) b

```

(Example currently in use in the Euclidean Algorithm)

**Comment by leios** [comment]
As far as haskell code is concerned, most of the code has been written by @jiegillet . To be honest, we were lacking haskell proficiency, so we may have not been reviewing the language as effectively as we could. This is a good discussion to have, thanks for bringing it up!

**Comment by julianschacher** [comment]
I think it should be in the style most Haskell programmers are used to, that would make the most sense for me. But let's get a discussion going, since I'm no Haskell expert by any means :)

**Comment by lulucca12** [comment]
I think we should try using this resources as a base [Ganeti code style guidlines for open source coding](http://docs.ganeti.org/ganeti/2.13/html/dev-codestyle.html#haskell) and [University of Pennsylvania](https://www.seas.upenn.edu/~cis552/current/styleguide.html) coding styles but cosider replacing the Haddock and documentation comments with text between code blocks, because we are already writing documentation, and using "hlin" before submitting code.

**Comment by lulucca12** [comment]
We could use also "brittany", "hindent" or "stylish-haskell" before submitting code

**Comment by lulucca12** [comment]
Hello @jiegillet I've seen your code style and I thought it was pretty good! There are some observations to make, thought: You normally state the types of your functions whats really good, but you should be clear of the type of Main too! Specially if you are trying to do some more advanced IO stuff. Your code style is very imperative like, this is great but it make code really big, so you could try using more composition and point-free styles to shorten it up, like in your code:
```haskell putStrLn $ "Length: " ++ (show $ length encoded) ```
that, as hlint suggested could be shortened to:
```haskell putStrLn $ "Length: " ++ show (length encoded) ```
to avoid $ and be in a more familiar way of coding.
Besides that, this are the only considerations I have to make.

**Comment by lulucca12** [comment]
Thank you for participating with the portability of the code to Haskell, and the application of new algorithms :smile:

**Comment by jiegillet** [comment]
It's my pleasure, I love Haskell. I've been teaching it in the last few months too ^^

**Comment by jiegillet** [comment]
@lulucca12, would you like to submit a PR with your changes to the Euclidian Algorithm? I can also do it if you prefer.
Also, would you be interested in a code review? I've just submitted #193 and it's usually hard for us to find people to review Haskell. No pressure obviously :)

**Comment by lulucca12** [comment]
@leios  @julianschacher  @jiegillet I am restarting the activity in this issue to note what we should do about the use of Style Guides and linting programs as a recommendation to make the code clear and
to ask if we need to open a new issue that is more generic about how we should make clear to new contributors (in the guidelines or somewhere else) the good habits of styling, linting and, maybe, code testing in all programing languages before submitting them (to insure code consistency), not just in Haskell.

**Comment by jiegillet** [comment]
We could put it in the Wiki.
There would be a general section (always have a main, maximum 80 characters wide, have consistent style, have explicit commit messages...) and subsections for different languages with links to style guides, prettifiers and whatever is good for that language.

**Comment by lulucca12** [comment]
Yes, I think this is great! I'll close this issue and open another one that focuses on the page itself in the wiki, not in the specific Haskell style.
