### ISSUE TITLE
Let's decide on how to indent JSON files

### ISSUE THREAD

**Issue by Butt4cak3** [algorithm-archivists/algorithm-archive#171]
During the latest pull request adventures, we had to add a few new languages to *book.json*. I noticed that the file is indented with tabs and we don't have an EditorConfig rule to reflect that. Some editors seem to indent JSON with spaces and that's why people could submit *book.json* edits with inconsistent indentation.

We have 3 options:
1. Keep tab indentation for *book.json* and make it a project-wide rule
2. Keep tab indentation for *book.json* as an exception and make space indentation the norm
3. Convert *book.json* to space indentation and make it a project-wide rule

What do you think?  I personally lean towards 3.

**Comment by julianschacher** [comment]
We currently use spaces everywhere else, so 3 seems reasonable.

**Comment by leios** [comment]
Yeah, when I was editing it, I thought we needed tabs for some reason. I figure having a spaces rule is fine.

**Comment by Gustorn** [comment]
2 or 4 spaces is the standard. Since we're using 2 for JS I think we should do the same for JSON.
