### ISSUE TITLE
Run JS examples

### ISSUE THREAD

**Issue by xam4lor** [algorithm-archivists/algorithm-archive#176]
Shouldn't we create a HTML file called `index.html` in the same directory as each JS file which just runs the JS code ?

Like this one :
```html
<!DOCTYPE html>
<html>
	<head>
		<title>JS Example</title>
		<script type="text/javascript" src="_JS-FILE_.js"></script>
	</head>

	<body></body>
</html>
```

**Comment by Butt4cak3** [comment]
Nope. We had this discussion a while ago and we decided not to include live demos.

**Comment by xam4lor** [comment]
Okay !
