### ISSUE TITLE
FYI: rosetta code

### ISSUE THREAD

**Issue by seriousme** [algorithm-archivists/algorithm-archive#185]
Maybe I'm stating the obvious, but just to be sure:  [Rosetta Code](http://www.rosettacode.org/wiki/Rosetta_Code) currently hosts  879 "programming tasks" in  697 languages.

Cheers,
Hans

**Comment by julianschacher** [comment]
Can you go in more detail about what you want to attack with this issue?

**Comment by Gathros** [comment]
Rosetta Code is focus is on languages and their differences which the archive is about the algorithms. Also the licencing on the code from Rosetta Code means you have to reference them when you use their code, we don't have that issue (if you want to call it an issue).

**Comment by seriousme** [comment]
No offence, I was just trying be helpful. The arguments from @Gathros make sense to me. It might be an idea to create a FAQ.md and list these arguments there so people know why to choose one over another.

**Comment by Gathros** [comment]
I understand, its just your comment made no sense; all you said was rosetta code and that's it. I guess you were trying to say the AAA is just another rosetta code.

**Comment by seriousme** [comment]
To be honest, I see so many people reinventing the wheel on the internet just because they don't know what's already out there. Hence my attempt to tell this community that other sites actually exist and my disclaimer that you might already be fully aware, which you obviously are. I've edited the title and will close the issue here. Good luck with the project !

**Comment by julianschacher** [comment]
@seriousme Thanks for the friendly help tho.

**Comment by julianschacher** [comment]
I've also created an FAQ entry regarding the difference: https://github.com/algorithm-archivists/algorithm-archive/wiki/FAQ#whats-the-difference-to-rosetta-code

**Comment by jiegillet** [comment]
I want to add that re-inventing the wheel is sometimes super fun and a good learning moment. Also, very rarely, the wheels ends up being perfected, so why not.
