### ISSUE TITLE
Ordering of languages is inconsistant

### ISSUE THREAD

**Issue by Jess3Jane** [algorithm-archivists/algorithm-archive#190]
It's a bit confusing currently to read which languages each example is in. For example C# is the first language on the Jarvis march page while C is the fourth. It'd probably be good to come up with a consistent ordering of languages, probably ordering the tabs alphabetically?

**Comment by julianschacher** [comment]
I try to write a little program sorting the stuff :)

**Comment by jiegillet** [comment]
I suggest the following ordering:
1. Scratch
2. Haskell
3. Whatever, I guess...

**Comment by leios** [comment]
You mean removing all other languages? Yeah. I could imagine a scratch algorithm archive.

**Comment by julianschacher** [comment]
We need to ask ourselves the following question: "Do we need any other languages than Scratch?"
And the answer is clearly "No!".
So I suggest making a PR just removing everything and adding Scratch implementations for every algorithm. Scratch to rule the world!

**Comment by jiegillet** [comment]
I'm on it! I honestly have previously implement around half of the algorithms of the AAA with Scratch.

**Comment by leios** [comment]
This has been fixed and is not pushed to the algorithm-archive.org (#220)
