### ISSUE TITLE
missing imaginary protion in FFT

### ISSUE THREAD

**Issue by earthfail** [algorithm-archivists/algorithm-archive#196]
I was reading FFT chapter and looking at

Xk=∑N−1n=0xn⋅e−2πkn/N
and
xn=1N∑N−1k=0Xk⋅e2πkn/N

where did the imaginary numbers go?
it was in the integral before and in the code after the discrete fourier transform

**Comment by leios** [comment]
This is a typo that was recently pointed out. Thanks for the catch!

**Comment by earthfail** [comment]
oh sorry for repeating
where was it pointed out?

**Comment by leios** [comment]
On discord chat, not here. Don't worry about it! I appreciate the help!

**Comment by Unlambder** [comment]
Opened a pull request to fix the issue.

**Comment by leios** [comment]
Fixed in #199 . 

Thanks @Unlambder !
