### ISSUE TITLE
Gauss elimination code (Julia) is wrong 

### ISSUE THREAD

**Issue by VikingScientist** [algorithm-archivists/algorithm-archive#201]
Basically
* Don't check for singularity as Gauss Elimination can be done on singular matrices
* Pivots are not neccessarily on the diagonal
* Cover the general case and don't assume triangular matrices

This issue affects PR #200 (contains more details on the bugs) and PR #195

**Comment by jiegillet** [comment]
#183 (which is already merged) is also wrong

**Comment by jiegillet** [comment]
The best is 4. In general, almost nothing you state in the chapter is wrong so it doesn't need that much rewrite. Back substitution DOES make sense in the case of singular matrices, you just need to travel through the pivots, not the diagonal. Again, very little rewrite, I believe. And yes, putting a couple more examples of non-physical examples will help with intuition.

I'm very happy to try and add something to my PR tonight, I've already modified the chapter anyway.

**Comment by leios** [comment]
Yup, sounds good. Please feel free to do what you can when you have the time.

**Comment by jiegillet** [comment]
I've modified the chapter over in #193
