### ISSUE TITLE
Julia code in FFT chapter

### ISSUE THREAD

**Issue by earthfail** [algorithm-archivists/algorithm-archive#226]
In the butterfly diagram were written
b0=a0+ω02a1
b1=a0−ω02a1

and from what I understand b_k=a(even)+w*a(odd)
but at the end of julia code in cooley_tukey function it says:

vcat(x_odd + x_even .* factor[1:half],
                x_odd - x_even .* factor[1:half])

I checked with wikipedia and other languages in this book that I understand and it is even indices plus omega*odd indices

**Comment by leios** [comment]
Hey @earthfail Yeah, you are right. The reason it was swapped in this case was because Julia starts indexing at 1.

**Comment by julianschacher** [comment]
Can this issue be closed? The question seems to be answered.

**Comment by leios** [comment]
Yup, closing now
