### ISSUE TITLE
Chapter Contributors

### ISSUE THREAD

**Issue by Gathros** [algorithm-archivists/algorithm-archive#34]
As discussed on discord, how many writers should there be?

Strawpol: https://strawpoll.com/53bxcwpf

**Comment by leios** [comment]
So, it looks like people are happy to have a few core authors (at least to start). I figure we should run a test-case for a second author on certain chapters soon.

If it works, then we can allow other folks to contribute chapters as they see fit.

**Comment by leios** [comment]
This should have been mostly addressed in #250 , so I will close this for now
