### ISSUE TITLE
Chapter submissions and planned revision

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#388]
Hey Guys,

I plan a large overhaul of the AAA in November, meaning that almost all chapters will be majorly changed and hopefully upgraded in terms of quality. During this process, the code should not change too much; however, I will need to update any chapter that is merged into the AAA before then. This includes chapters that I have not actually written (#163, #216, #278, #346, #358). By this, I mean that if these chapters are merged before the revision, they will need to be updated in the revision process.

I'm honestly not sure the best way to proceed here, but I believe the best option is to put chapter PR's on hold until the quality of the AAA improves and we have a set standard to work from.

Right now, I strongly feel that the AAA is lacking in quality in most cases. This is not okay and it is my fault. I need to fix it before the AAA gets too big. That said, I apologize for all the unnecessary work put into those PR's so far. They will be merged eventually, but I feel we should wait until after a new standard of quality has been created for the AAA. 

I am definitely up for discussion here.

Here is a link to a list that will be updated soon: https://docs.google.com/spreadsheets/d/1TAHkVG5FyvXKyBQVPRO54ZpVcM5kUm9KhKH9LhTVP9I/edit?usp=sharing

**Comment by leios** [comment]
Quick note on this. Because Hacktober is coming up, I might move these revisions into next month instead. I wanted november for a NaNoWriMo theme, but Hacktober is probably a bit more in-line with the project.

I would like to create a "How to Contribute: Chapter Edition" guide that shows what the review criteria is for chapters and explains a few things about it (including licensing and such).

**Comment by Amaras** [comment]
@leios Do you have a set standard for chapter quality, or should we put this issue on hold?

**Comment by leios** [comment]
I think we are able to close this issue now. Though all chapters are not up to snuff, most of the recent ones are quite good and we are slowly distributing that to older chapters (FFT, for example). Thanks for bringing this up!
