### ISSUE TITLE
mult-lang explanation / how to contribute

### ISSUE THREAD

**Issue by julianschacher** [algorithm-archivists/algorithm-archive#40]
We should have a comprehensive how-to-contribute file, which includes documentation on how to use the theme-api with the book.json.

**Comment by leios** [comment]
Agreed. This is on the list of things to do and will be done soon... definitely before the next update video. =)

**Comment by julianschacher** [comment]
This issue got solved with the addition of the [How to Contribute Wiki Article](https://github.com/algorithm-archivists/algorithm-archive/wiki/How-to-Contribute) and the addition of the [Contributing.md](https://github.com/algorithm-archivists/algorithm-archive/blob/master/CONTRIBUTING.md) (in <https://github.com/algorithm-archivists/algorithm-archive/pull/286>).
