### ISSUE TITLE
Creative Commons text license handling

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#493]
As of right now, I (James Schloss) have exclusive commercial rights over the text in the Algorithm Archive (AAA). This was done deliberatively at the start of the project because I thought I would be the only author; however, since we have chapter submissions, this will no longer be the case and we need more rigorous chapter contribution guidelines along while also providing a license that "makes sense for each chapter."

I will explain the problem in as much depth as I can, so please forgive the length of this post.

### **Long-term goal:**

I would like to be able to create a Print-on-Demand version of the AAA. Users select the chapters they want published and the language, and we print them physical copies. We should also provide guides through different topics (Like a "Guide to Computational Physics" or something), which provide a pre-bundled selection of chapters and some auxiliary text exclusive to each guide.

This is the only way I can actually see the AAA being sold, but I put the Non-Commercial tag in the Creative-Commons license because I didn't want people printing unofficial AAA copies and selling them.

### **The main problem:**
There has been some discussion about whether the Non-Commercial is actually necessary in this case because:

1. It inhibits the freedom of others to sell the work and is thus less free according to Free Software Foundation standards.
2. If we do sell the book in the way described above, all the funds would go to me, not the algorithm-archivists group, which is notably unfair.
3. I don't think printing the AAA is generally possible without some sort of Print-on-Demand service that we work on together with a specific publisher. It might not actually be possible for other people to print the book in a reasonable way without negotiating with us directly.

In addition, we have one license over the entire AAA text (similar to how we have one license over all the code). If someone submits a new chapter to the AAA, they should be attributed for their work on the chapter. If someone edits the chapter, they should also be attributed. This is not currently how our CC license works.

### **Possible solutions to Non-Commercial problem:**

No matter the case, the Non-Commercial tag seems unnecessary in this case; however, the discussion also came up about using Share-Alike instead. Share-Alike just means that any forks / modifications of the AAA must use the same license. It's one of those "more free licenses that also enforces freedom," so it is somehow more restrictive in another sense. I am 50:50 on the Share-Alike right now.

### **Possible solutions to authorship problem:**

The authorship problem is a bit harder to tackle. We could do a number of things:
1. Keep a global licence, but change it to be attributed to `James Schloss et. al.` and define the `et. al.` to be in a separate file called `AUTHORS.md`, similar to `CONTRIBUTORS.md` for the code. If someone modifies the text, they can just put their name there. This has the advantage of only being in one place, so we don't need to put the license in every chapter online (and in print eventually).
2. Have a separate license for each chapter. This allows us to be more specific about attribution for each chapter, but is a little harder to keep track of.

There are probably other solutions here that we discussed, but I missed. Please let me know and I'll update this.

### **Conclusion:**

My current opinion is that we should remove the Non-Commercial tag in the license and share the license between everyone in a global `AUTHORS.md` file. If we want to sell bundled versions of the AAA later, this is perfectly fine without the Non-Commercial tag. As I mentioned, I am still 50:50 on the Share-Alike, but if you guys want it, I don't mind putting it in there.

Please let me know what you guys think about this. It's kinda messy, but we need to get it right before merging chapters into the AAA.

**Comment by julianschacher** [comment]
HappyLittleRat also had the idea of asking the CC folks for advice.
I think that's a good idea and the issue here can double as a preparation, so that we know, what our goal is and which questions we want to ask.

**Comment by leios** [comment]
I agree. That was part of the reason I tried to explain everything in sufficient depth.

**Comment by julianschacher** [comment]
### ShareAlike

I'm also 50/50 on ShareAlike. While it is a good tool to make sure, that every modification of the AAA and therefore the ideas and work of the AAA stay open, it might be a problem if, let's say, a teacher wants to use a text snippet of the AAA as part of a text in school, which they can't ShareAlike for some reason.

The question is here: Does including a text snippet trigger the ShareAlike or is it just triggered, if you release a modified version? If it's the first case, I think we shouldn't use ShareAlike, if it's the second however, ShareAlike seems to be a good option.

### Global or Local License

I think we should license each chapter locally. By doing so, we keep the list of authors short and don't have one bloated contributors file.
Using the chapter text and giving attribution is also easier, because you just have to mention 4-5 people instead of 50-60.

### Minor Changes

If I understand it correctly, each modification of the text would produce a new modified version of it, which requires attribution to the new author. While this is absolutely fine for text revisions and additions, this would also mean, that each fixed typo would result in a new contributor added to the authors.
This isn't too much of a problem, but it does treat the people, who did much work, equal as people, who just fixed a typo.

### The Contribution Process

Another question is, how the contribution process would work with the license. Does stating that all texts are licensed under CC-BY-SA implicitly makes the author of a PR publishing their text / modification / typo under the license or do we need them to do this explicitly?
(If the second case is true, we would have to get every past contributor of the AAA to explicitly publish their modification under CC-BY-SA)

**Comment by leios** [comment]
**Share-Alike /  Non-Commercial:**

I honestly think Share-Alike is predatory and shady, but I understand that it prevents people from taking the book, modifying the license, and then selling it. The Non-Commercial is much more straightforward and usable for this purpose. It just says, "Hey. You can do what you want with this, but you cannot sell it unless you are one of the people listed here." Share-Alike says, "You can use this, but only in the way we want you to." It boggles my mind that the FSF thinks the former is somehow less free than the latter, but I didn't draw the lines here.

Again, I really don't care that much... It's just that Share-Alike bugs me a bit.

I think the teaching question is only related to teachers that want to take the AAA and distribute lecture notes (or something) online. Even then, we cannot police local distribution. If they want to share it in a public forum (maybe a note website of sorts), then the modification would need to be CC.

**Global or local license:**

I think the local license is harder to maintain and it means that if we print a book, every single chapter will need a separate license to be printed. That's not that big of a deal, honestly. I think it's a good idea to attribute the algorithm-archivists and invite anyone who has a chapter submitted to the organization, itself. I don't know if this means we need an actual company or if a github organization would do.

A global author file would be easy enough to create a license for: 
```
Terms of Use: This text is licensed under a Creative Commons Attribution License 4.0. It is attributed to all authors in [Link to file].
```

Alternatively, if we claim the algorithm-archivists organization, it's:
```
Terms of Use: This text is licensed under a Creative Commons Attribution License 4.0. It is attributed to the algorithm-archivists organization.
```

For individual chapters, this might look like:
```
Terms of Use: This text is licensed under a Creative Commons Attribution License 4.0. It is attributed to the James Schloss and the algorithm-archivists organization.
```

Again, that's fine to put on each webpage and isn't too annoying to print. We just need to remember to update the license for each chapter.

**Minor changes:**

I feel like people who make minor changes should be acknowledged, but we can do it like we said above:

```
Terms of Use: This text is licensed under a Creative Commons Attribution License 4.0. It is attributed to the James Schloss and additional authors in [Link to authors file].
```

Or even:
```
Terms of Use: This text is licensed under a Creative Commons Attribution License 4.0. It is attributed to the James Schloss and [other folks].
```

The problem is that if we update the license in the latter way (as more people come in), I am afraid we will need to get the permission of the original author, and that might be hard to do in some cases. By saying we have a global list of authors / reviewers, it is clear from the license initially that the initial author will allow modification from anyone on the changing list of authors.

**Contribution process:**

Clear guidelines are necessary, but having a in-build PR template for code submissions and chapter submissions with a box that says, "I accept that this contribution will be under this license." is a good idea going forward.

**Comment by julianschacher** [comment]
### Share-Alike / Non-Commercial

I very much understand the thought process of the FSF behind SA and NC, but that doesn't really matter for this discussion.

I would love to see the AAA being fully free, but I know about the risk, that not-NC (and not-NC in combination with not-SA), introduces.
So we should consider using NC.

### Global or local license

The algorithm-archivists organisation doesn't necessarily consists exclusively of all authors. If you want a global license a file with the contributors seems more reasonable.

If we want to print the book, local licenses aren't really a problem. I think a smart solution can be figured out. For more info, look [here](https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en) under "Offline Work?".

[This page](https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en) also suggests, that we don't need to include the CC license we're using. Linking to it seems fine.

**Comment by Butt4cak3** [comment]
> It inhibits the freedom of others to sell the work and is thus less free according to Free Software Foundation standards.

I just want to point out that I do not have a problem with that. I think the NC license fits this project. During today's stream, all I tried to say is that that's part of the FSF's definition of free.

**Comment by leios** [comment]
I don't want get into the SA debate again. I stand by what I said before. I am sketched out by it, but if everyone else wants to use it, we can use it.

I still think the NC works here, but if we do individual licenses with different authors on every chapter, it becomes difficult to create a physical copy eventually because when we do, we need to contact all the authors who might have moved on. This is why a global attribution to the algorithm-archivists makes sense. We can then funnel all the money to the organization, instead of individuals, and then pay the individuals for dev time.

I think it's alright to give attribution to everyone in the organization (for writing, reviewing and facilitating code contributions), but leave the small edits in `CONTRIBUTORS.md`. After all, the text and code go hand-in-hand.

No matter the case, we need to make attribution clear in the chapter contribution guide.

I have no idea how to deal with SA with non-SA. Honestly, I just want to do whatever causes us the least stress in the future.

**Comment by julianschacher** [comment]
## ShareAlike

If ShareAlike prevents the AAA from being used in educational scenarios (being incompatible with text-snippets from other papers and so on), we shouldn't use it. One key-goal of the AAA is enhancing educational content.

### NonCommercial

I also think NC makes sense. The risk of companies abusing the AAA is just too high and the AAA organisation is so small, that we can't prevent it.
I think tho, that we should somehow reserve the possibility of making the AAA not-NC at a later point.

### Global or Local License

After thinking about it, a global license seems nicer, since the AAA is licensed as a whole. Just relicensing on every text change doesn't seem to bad. (We just need to make sure to preserve NC somehow (,if we want to use it).)

**Comment by leios** [comment]
I think I have changed my mind here. The only way for us to have exclusive commercial rights is with NC, but it seems like the NC license does more than what the wording of the license implies ([here's a graphic to explain what I mean](https://meta.wikimedia.org/wiki/File:Open_Content_A_Practical_Guide_to_Using_Creative_Commons_Licences_web-46.png))

I want the AAA to be used by as many people as possible. I just wanted to make sure people didn't sell a copy of the AAA to make a profit off the community without our explicit permission.

I figure that it is a lot of work to take the current AAA and sell it, so it's probably fine to make everything SA so we can sell our own version (and I guess other people can sell a version too, but I doubt other people will).

In order to keep the NC, we need to either cede commercial rights to me for the time being or create a company to have the commercial rights (which would be hard for me to do right now). It doesn't make sense to have more than one entity have exclusive commercial rights over different parts of the book.

**Comment by leios** [comment]
I believe most people are now more or less okay with the idea of re-licensing all AAA content under CC BY-SA, which can be done because I have exclusive rights over all written content right now. The main reason I am no longer in favor of NC is that under NC, the AAA cannot be used in tuition-based courses... Which is a bit restriction.

After this change is made, we can begin attributing authors and editors at the bottom of each chapter.

In principle, the CC BY-SA license will allow anyone to print and sell copies of the AAA, but we will assume that they either will not do this or that we can provide a copy for less because we are not intending to make a profit off AAA sales.

I will make this change soon, but would like to hear any further discussion before then.

**Comment by leios** [comment]
I was going to wait for the merge of the PR templates in #569

**Comment by leios** [comment]
The only reason this issue is not closed is because the PR templates are not working right now. I will close this and open a new issue for PR templates
