### ISSUE TITLE
Unintuitive Directory Scheme

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#57]
Currently, the Algorithm Archive is divided into large algorithmic "domains" of `computational_physics`, `computational_mathematics` and so on. I wrote it this way so that readers could easily learn about that topic of interest when it was sufficiently filled with algorithms. For example, if someone wanted to learn about computational physics, they just go to that section. 

The problem here is that many of the algorithms in `computational_physics` could easily belong in `computational_mathematics` or other areas, so instead of providing large overarching directories, it might be better to divide those sections up into individual components (like `ODE_solvers` or something), and then provide an "algorithmic guide to computational physics" at the start, which provides commentary through all the different algorithms and methods in computational physics (kinda like a large outline for those who want to learn the topic).

These guides would be written after we have a sufficient number of algorithms in the Archive, so it will be a while, but I wanted to create an issue to keep this in mind and see if anyone has a better idea on how to organize this project. As always, I am open to suggestions!

**Comment by jiegillet** [comment]
Out there suggestion: apply some unsupervised machine learning techniques to the wikipedia pages of all the algorithms to group them into 4 categories, and figure out how to call them from that :)

**Comment by leios** [comment]
Huh. I kinda like that idea. It would be neat to use one of the methods we eventually cover here to organize the algorithm archive. 

This will take some time to do, though. So for now, I think we should do something simple. 

It doesn't necessarily need to be `n = 4` categories either. We can use affinity propagation (or something) to split it up more organically.

**Comment by jiegillet** [comment]
Agreed, that's a fun project for later :)
Quick research on how people are doing it elsewhere: [here](https://github.com/nryoung/algorithms/tree/master/algorithms), [here](https://github.com/iiitv/algos) or [here](https://github.com/TheAlgorithms/Java)

**Comment by leios** [comment]
I actually left it open because it's still not quite right. I am missing the guides and am not happy with certain sections (like convolutions) just lying about in the chapters directory. This should probably go into a mathematical methods section or something.

I just feel like it's still a work in progress.

**Comment by julianschacherpp** [comment]
Ok

**Comment by Butt4cak3** [comment]
Can this be closed now that #242 is merged?
