### ISSUE TITLE
Open a merge sort chapter and I can start with a JS and Ruby implementation of it.

### ISSUE THREAD

**Issue by Amjad-H-Ali** [algorithm-archivists/algorithm-archive#590]
Open a merge sort chapter and I can start with a JS and Ruby implementation of it.

**Comment by leios** [comment]
Sorting methods are not on my priority list here. They are certainly important, but most sorting algorithms are well-explained elsewhere. That said, if you want to open a merge sort chapter, you can do so as soon as #569 is merged. It might be a lengthy review process, though.
