### ISSUE TITLE
Mistake in the gaussian elimination chapter.

### ISSUE THREAD

**Issue by Trashtalk217** [algorithm-archivists/algorithm-archive#592]
At **The Computational Method** -> **Step 2** there is a mistake in the first calculation.

instead of:
```
f = A(pivot_row, pivot_col) / A(curr_row, pivot_col)
  = 1/3
```
it should be:
```
f = A(curr_row, pivot_col) / A(pivot_row, pivot_col)
  = 1/3
```
Because the pivot value is 3 and the current value is 1, resulting in 3/1 in the first equation.

**Comment by leios** [comment]
Fixed in #593
