### ISSUE TITLE
Language selector of aaapy doesn't work

### ISSUE THREAD

**Issue by Liikt** [algorithm-archivists/algorithm-archive#615]
# Bug Report

## Description

Kudos firstly to @Neverik for rewriting the AAA. Looks pretty good so far. 

I found a small bug though. The language selector doesn't work for `x86` and `Scratch` doesn't work. 

### Steps to Reproduce

1. Go to https://aaapy.herokuapp.com
2. Click on the FFT Chapter
3. Select either `x86-64 Assembler` or `Scratch`
4. Nothing Happens

### Expected behavior

The language displayed should switch to the selected one.

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by leios** [comment]
aaa-py is not officially part of the algorithm archive yet. I agree that it's a great project though and seems like a good direction to go in.

Maybe this issue should be opened there? Link: https://github.com/Neverik/aaa-py

**Comment by Liikt** [comment]
That is a good idea. Will do!
