### ISSUE TITLE
pdf export / print

### ISSUE THREAD

**Issue by dadosch** [algorithm-archivists/algorithm-archive#665]
# Bug Report
When I try to print a webpage using firefox or chrome, only the first page is printed. Maybe this is a gitbooks issue, so it would be handy to have pdfs of each article which one could download.

### Steps to Reproduce

1. Go to 'https://www.algorithm-archive.org/contents/gaussian_elimination/gaussian_elimination.html'
2. Show print preview of firefox/chrome

### Expected behavior

the full webpage should be shown or there should be a pdf available to download.

## For Algorithm Archive Developers

- [x] The bug can be reproduced
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [x] There is a timeline to fix the bug
- [x] The bug has been fixed (Please link the PR)

**Comment by leios** [comment]
Right, we do not have pdf exporting available right now and we need to think about how we might do this. For now, we cannot really tackle this issue until we switch to something other than gitbook (or find a better way to make gitbook work for us)

**Comment by leios** [comment]
This has been fixed in #777 (I just forgot to close the issue). Thanks for bringing it up!
