### ISSUE TITLE
Certain language not carrying over different chapters

### ISSUE THREAD

**Issue by Colocasian** [algorithm-archivists/algorithm-archive#670]
# Bug Report

## Description

If someone selected a specific language in certain chapters, and then moved on to another chapter, the language would not be carried over to the other chapter, even if an implementation in the same language exists. Like, if one was looking at the C++ implementation of Bogo Sort, then he moved on to Euclidean Algorithm, the archive would still show the C++ implementation here instead of the default (i.e. Julia). But this doesn't work for certain languages. The problem is regarding the inconsistency in the tags used for the lang markers in the markdown files for each chapter (i.e. the `{% sample lang="<language>" %}` for the sample).

### Steps to Reproduce

1. Open up AAA (at www.algorithm-archive.org or local build).
2. (Although this problem exists for other languages too, demonstrated using JavaScript) Open up the Verlet Integration Chapter and select JavaScript as the Implementation language.
3. Now, go to any other chapter which contains a JavaScript Implementation (such as Bogo Sort).
4. We see that the language falls back to default (i.e. Julia), even though JavaScript implementation exists.

### Expected behavior

We expect to see that here, the JavaScript implementation will be shown. But rather, the default language (i.e. Julia) will be shown. The same problem occurs for the given languages when moving from the listed chapters to any other chapter, even if it has an implementation in the same language:

- Euclidean Algorithm: Haskell
- Verlet Integration: JavaScript
- Verlet Integration, Euclidean Algorithm: Matlab

## Environment

 - OS: GNU/Linux (Gentoo)
 - OS Version: Linux kernel 4.19.97, Gentoo base system 2.6
 - Browser: Tested on Firefox ESR (Should occur on any browser)
 - Browser Version: Firefox 68.5.0esr

## Additional context

I have created a PR, fixing the issue. There, there is extra info regarding the issue and how I fixed it. Link: https://github.com/algorithm-archivists/algorithm-archive/pull/669

## For Algorithm Archive Developers

- [x] The bug can be reproduced
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [x] There is a timeline to fix the bug
- [x] The bug has been fixed (Please link the PR)

**Comment by leios** [comment]
This issue has been fixed in #669. Good work!
