### ISSUE TITLE
Themes make some content difficult to read

### ISSUE THREAD

**Issue by stormofice** [algorithm-archivists/algorithm-archive#711]
# Bug Report

## Description

Using the "Sepia" or "Night" colour theme leads to some text being barely readable. This is most noticeable on the text in the search box ("Type to search") and the results when searching for a topic.

## Screenshots
Search box:
Sepia:
![firefox_JNC3BFQmYZ](https://user-images.githubusercontent.com/58337328/83575439-bf50a200-a52f-11ea-9632-b6e5084518d8.png)
Night:
![image](https://user-images.githubusercontent.com/58337328/83575457-ce375480-a52f-11ea-9e64-3f93185ea854.png)
Search results:
Night:
![image](https://user-images.githubusercontent.com/58337328/83575501-e8713280-a52f-11ea-842b-5038ea58fcdc.png)

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by c252** [comment]
Thanks for the submission! We are currently switching the archive from Gitbook to AAAbook, this should solve this (and the other) issues you have brought up.

**Comment by Iinguistics** [comment]
AAAbook?

**Comment by stormofice** [comment]
This got fixed due to the PRs.
