### ISSUE TITLE
Clicking the twitter button does nothing

### ISSUE THREAD

**Issue by stormofice** [algorithm-archivists/algorithm-archive#713]
# Bug Report

## Description

Instead of "pre-creating" a tweet when clicking the twitter share button, nothing happens.
The link that is created looks like this:
`https://twitter.com/home?status=[article name] [article url]`
This can be fixed by changing the link to:
`https://twitter.com/intent/tweet?text=[article name]&url=[article url]`

### Expected behavior
Something similar to this happens:
![image](https://user-images.githubusercontent.com/58337328/83576986-59661980-a533-11ea-86a3-bcd72a87451c.png)

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by leios** [comment]
Thanks a bunch for opening these issues!

**Comment by leios** [comment]
This can be closed thanks to honkit removing the twitter button.
