### ISSUE TITLE
The Python implementation of the Euclidean Algorithm by subtraction hits an infinite loop when a = 0

### ISSUE THREAD

**Issue by thecnoNSMB** [algorithm-archivists/algorithm-archive#740]
# Bug Report

## Description

As stated in the title. This is due to it endlessly subtracting 0 from the other number to no effect. To reproduce, call `euclid_sub(0, 1)` in [euclidean_example.py](https://github.com/algorithm-archivists/algorithm-archive/blob/master/contents/euclidean_algorithm/code/python/euclidean_example.py).

## Additional context

This bug was found using the Python property-based testing library Hypothesis.

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by valdaarhun** [comment]
Hi. I am new to open source and would like to work on this issue.

**Comment by Amaras** [comment]
> Hi. I am new to open source and would like to work on this issue.

Hi! Thanks for you interest in the AAA.
What you can do is fork this repository, and work on your local copy to fix this issue. Once the issue is fixed, you can submit a PR.
The more detailed contribution guide can be found [here](https://github.com/algorithm-archivists/algorithm-archive/wiki/How-to-Contribute)

**Comment by valdaarhun** [comment]
Hi. I tried running the commands given in the guide but am faced with a problem. When I run `gitbook install` everything seems to be fine. All the plugins are installed as they are supposed to be. I have attached a screenshot for your reference below. 
![1](https://user-images.githubusercontent.com/39989901/91994067-c61bca80-ed53-11ea-82ee-fd9f03c15288.JPG)

However, when I run `gitbook serve`, I seem to get a plugin-related "module not found" error as shown in the screenshot below. 
![2](https://user-images.githubusercontent.com/39989901/91994283-11ce7400-ed54-11ea-9aa7-e6311cb3840e.JPG)

Do you know why this problem arises?

**Comment by thecnoNSMB** [comment]
That fixed it, thanks!
