### ISSUE TITLE
"How to Contribute" guide on the wiki is outdated since the AAA switched to HonKit

### ISSUE THREAD

**Issue by 0xJonas** [algorithm-archivists/algorithm-archive#778]
# Bug Report

## Description

The guide 'How to Contribute' on the AAA wiki still talks about Gitbook instead of HonKit and should be updated.
The sections that need to be changed are steps [1.2 (Gitbook)](https://github.com/algorithm-archivists/algorithm-archive/wiki/How-to-Contribute#step-12---gitbook) and [2.3 (Building and running the AAA)](https://github.com/algorithm-archivists/algorithm-archive/wiki/How-to-Contribute#step-23---building-and-running-the-aaa).

Also, I am not sure if there is an equivalent to `gitbook install` in HonKit. Either way, it is enough to just run `npm install` (without any arguments) after cloning the AAA fork which will install HonKit as well as all the required plugins.

### Steps to Reproduce

1. Go to https://github.com/algorithm-archivists/algorithm-archive/wiki/How-to-Contribute
2. There's Gitbook

## For Algorithm Archive Developers

- [x] The bug can be reproduced
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [x] There is a timeline to fix the bug
- [x] The bug has been fixed (Please link the PR)

**Comment by leios** [comment]
This issue has been fixed (I think), so please go to the [How to Contribute](https://github.com/algorithm-archivists/algorithm-archive/wiki/How-to-Contribute) wiki to check it out.

Closing for now, but please let me know if it is not up to snuff!
