### ISSUE TITLE
Is this project still alive and can I add Scala to the language list ? :D 

### ISSUE THREAD

**Issue by tnlong1997** [algorithm-archivists/algorithm-archive#791]
# Chapter Request

## Description

A clear and concise description of what the new algorithm, method or data structure would be about, including links to the relevant academic articles or sources.

## Additional context

Add any other reasons why this chapter should be a higher priority.
Delete this section, if you don't think the chapter is of a high priority.

## For Algorithm Archive Developers

- [ ] This chapter can be added to the [Master Overview](https://github.com/algorithm-archivists/algorithm-archive/projects/11) (if it cannot be, explain why in a comment below -- lack of sufficient technical sources, not novel enough, too ambitious, etc.)
- [ ] There is a timeline for when this chapter can be written
- [ ] The chapter has been added to the [Master Overview](https://github.com/algorithm-archivists/algorithm-archive/projects/11)
- [ ] The chapter has been written (Please link the PR)

**Comment by leios** [comment]
The project is still alive, but was on life support for the past few *cough* years... But I will be focusing on it way, way more in 2021, so expect it to grow a lot!

As for the Scala language, there are already chapters with scala in them and a few PRs for scala. If you want to add a new language implementation, please check to make sure you are not doubling up first.

**Comment by tnlong1997** [comment]
@leios thanks for clarification :D I will close this issue
