### ISSUE TITLE
Scaling along y in 'Affine Transformations' not right?

### ISSUE THREAD

**Issue by rduivenvoorde** [algorithm-archivists/algorithm-archive#801]
Hi, not 100% sure, in but the second animation (scaling along y) in the section about 'Affine Transformations' 

https://www.algorithm-archive.org/contents/affine_transformations/affine_transformations.html

I could not see the difference with the one about 'scaling along x'... both seem to change the upper left element of the matrix:

![Screenshot-20210303132030-931x479](https://user-images.githubusercontent.com/731673/109805425-b3f7e780-7c23-11eb-9537-5e13db1f9083.png)

Then in the the video:
https://www.youtube.com/watch?v=E3Phj6J287o&feature=emb_imp_woyt
you see the same steps, but then the lower right corner element of the matrix is used to change the scaling of y

![Screenshot-20210303132508-796x559](https://user-images.githubusercontent.com/731673/109805656-0507db80-7c24-11eb-9510-62fac8f78322.png)

Is it possible that the first mentioned animation is wrong?

**Comment by leios** [comment]
Thanks! I'll fix this in a few hours! Not quite sure how that happened...
