### ISSUE TITLE
Bibtex-cite plugin jumping to top of page

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#809]
# Bug Report

## Description

bibtex citations now link to the top of the page when clicking in the article; however, copying the link and going to that address separately will bring you to the appropriate citation

### Steps to Reproduce

1. Go to https://www.algorithm-archive.org/contents/computus/computus.html
2. Click on any citation
3. past link into browser to find correct citation

## Notes

Potential fix for honkit (bibtex-cite plugin): https://stackoverflow.com/questions/3252730/how-to-prevent-a-click-on-a-link-from-jumping-to-top-of-page

## Environment

 - OS: Arch
 - Browser: Firefox, QuteBrowsery
 - Browser Version: [88,v2.2.1]

## For Algorithm Archive Developers

- [x] The bug can be reproduced
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [x] There is a timeline to fix the bug
- [x] The bug has been fixed (Please link the PR)

**Comment by MambaDev** [comment]
Resolved in #815
