### ISSUE TITLE
[Github organisation proposition] Rename `master` branch

### ISSUE THREAD

**Issue by Amaras** [algorithm-archivists/algorithm-archive#810]
Following all the discussions in many open source projects' communities, I wonder if we should also get rid of the `master` terminology.
I guess the default now is to call the default branch `main`, with projects as big as Python renaming their `master` branch (and only breaking GitHub once in the process).
So, what do you guys think of that change?

**Comment by ntindle** [comment]
This will also require updating the workflows, just a find-replace `master` -> `main`

**Comment by ntindle** [comment]
Is this something we are in favor of? If so assign to me @leios
