### ISSUE TITLE
Bibliography does not render correctly

### ISSUE THREAD

**Issue by stormofice** [algorithm-archivists/algorithm-archive#837]
# Bug Report

## Description

Every second line of the bibliography does not get rendered correctly. In the default white theme it gets rendered as light grey, but this doesn't change in the other themes (so it stays light gray instead of light blue for example).

### Steps to Reproduce

1. Go [the approximate counting chapter](https://www.algorithm-archive.org/contents/approximate_counting/approximate_counting.html) (or any other chapter which uses the bibliography)
2. Scroll down to bibliography
3. See error

### Expected behavior

Every second line gets rendered in a lighter version of the theme background color.

## Screenshots

White theme:
![image](https://user-images.githubusercontent.com/58337328/130375396-015faf6b-8e54-4969-8b7e-d0c0ecf7514b.png)
Sepia theme:
![image](https://user-images.githubusercontent.com/58337328/130375415-2c359e45-e879-4ca0-bd55-80528bc8a330.png)
Night theme:
![image](https://user-images.githubusercontent.com/58337328/130375405-aa196cd0-8ccf-464b-98ea-d43fb4318a20.png)

## For Algorithm Archive Developers

- [x] The bug can be reproduced
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [x] There is a timeline to fix the bug
- [x] The bug has been fixed (Please link the PR)

**Comment by leios** [comment]
https://github.com/algorithm-archivists/gitbook-plugin-bibtex-cite/pull/2 <--- I believe this should fix this issue the next time the AAA is built. Thanks!
