### ISSUE TITLE
Should have take absolute value

### ISSUE THREAD

**Issue by mika314** [algorithm-archivists/algorithm-archive#843]
If the expected value is greater than calculated the test will give a false positive.

https://github.com/algorithm-archivists/algorithm-archive/blob/7ec4fc5d980f686f3e81f38f0230152686dcf318/contents/approximate_counting/code/julia/approximate_counting.jl#L50

**Comment by leios** [comment]
Right, we should be using abs. Thanks again for the catch! I'll update the Julia code in #840
