### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#870]
We are currently looking for projects that would be good for hacktoberfest 2021.

For those looking for hacktoberfest projects: If there is an algorithm that is missing an implementation in your favorite language, feel free to add it in! Also if there is a PR up for a language that you know, feel free to do a review and let me know if the syntax is good or not!

Issue suggestions:
#871 #906 

Outside of that, there might be additional projects in this thread from other algorithm archivists who have a good idea of what to do!

**Comment by leios** [comment]
Unfortunately, we are not accepting new algorithm submissions at this time, just implementations. We have gone back and forth and might be able to accept some when we get through the backlog of other chapter submissions, but right now I don't have the bandwidth for chapter reviews.

**Comment by Amaras** [comment]
Once the SCons PR is merged (#885), I will open a Hacktoberfest SCons issue in order to let contributors add languages to the compilation instructions and have it count for their Hacktoberfest total. :smiley:

**Comment by Amaras** [comment]
I'll close this for now, since this one is specific for 2021. I'll also unpin it for now.
We should remember it for next year, but it's not very useful for now.
