### ISSUE TITLE
Leaving gitbook

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/algorithm-archive#90]
Hey Guys,

We found out recently that gitbook is planning to stop supporting its current version and will be moving to a proprietary system without plugins. We need plugins and strongly prefer open source. In addition, they are turning off the legacy gitbook servers soon.

After talking to support about this, we came to the conclusion that we should move the Algorithm Archive off of the gitbook site. The easiest solution to this is to create a new algorithm archive organization (and corresponding github pages site), which has a few benefits:

1. We can fork the legacy gitbook repos and plugins for when / if they go down (est. 6 months)
2. We can give people more permissions so they can more quickly handle PR's and can modify their own projects
3. We can use a github pages page for the algorithm archive for now on (algorithm-archive.github.io)

There was a lot of talk about this on discord, but I failed to discuss this on gitbhub. The plan is to create this organization soon and shift everything to the github url then too.

Please feel free to discuss alternative solutions here.

**Comment by Butt4cak3** [comment]
I'll just use this as a place to post issues regarding the migration process.

The description field of the repository still contains the link to the old gitbook That should probably be updated to the GitHub page.

**Comment by leios** [comment]
Fixed. I missed that when going through all the links.

**Comment by nikhiljha** [comment]
Isn't Gitbook open source? It won't be maintained, but that's the beauty of open source. Just because they're turning off the servers doesn't mean you can't build the book locally and host it on GitHub Pages or something.

**Comment by nikhiljha** [comment]
Alternatively, we could build a simple tool to do this with a static site generator. There are [quite a few](https://www.staticgen.com) and all of them are fairly easy to configure. This would allow for a more robust organizational system for the algorithms too.

**Comment by leios** [comment]
@nikhiljha You are right, gitbook is open source and we have everything we need forked under the algorithm archivists group, just in case. I think the migration process is complete.I think the algorithm-archive.org is a great place for now, at least. We just need to remember to build the site and put it to the algorithm-archivists.github.io repo every now and again.

 I had this issue up for a bit for people to voice concerns, but it doesn't seem like there are any more coming in. 

Out of curiosity, how can we " allow for a more robust organizational system for the algorithms"? Do you mean that we can more easily build our own tools to go with the site and such?

**Comment by Butt4cak3** [comment]
@nikhiljha For clarification: We're already doing what you suggested. The book is hosted on [GH pages](https://github.com/algorithm-archivists/algorithm-archivists.github.io), running a [forked version of gitbook](https://github.com/algorithm-archivists/gitbook).

**Comment by nikhiljha** [comment]
> Out of curiosity, how can we " allow for a more robust organizational system for the algorithms"? Do you mean that we can more easily build our own tools to go with the site and such?

@leios Well it wouldn't be Gitbook anymore, so you could layout the site however you want. Examples: A homepage that breaks algorithms down into different categories of what they do, a search function, etc.

Having a giant repository of every algorithm in every language would quickly get unwieldy in a book format.

**Comment by Butt4cak3** [comment]
@nikhiljha This kinda sounds like reinventing the wheel to me. I think we have a pretty decent system in place. It has a bit of overhead (e. h. code imports), but it's not too much to handle, especially if contributors do these things in their PRs.

**Comment by nikhiljha** [comment]
@Butt4cak3 For sure it's easier to stay with Gitbook in the short term, but we're already running into problems that would be trivial to fix if we were using a different SSG (see #57 #102). Luckily though, most SSGs (like Gitbook! 😃) work basically the same as all others. 

I think I'll play with a script to port the repository over to a different SSG format. It shouldn't be hard because Markdown is basically 1:1 except for the code imports. I'll report back with how it goes.

**Comment by leios** [comment]
@nikhiljha You're right, we are basically using gitbook because it worked for some time and with some plugins does what we need it to do. What other SSG's do you have in mind?

**Comment by nikhiljha** [comment]
[Hugo](https://gohugo.io) is most definitely the easiest, but [Gatsby](https://www.staticgen.com/gatsby) or [Next](https://www.staticgen.com/next) might be easier to customize and have a huge library of neat plugins already made.

**Comment by MarcoPorracin** [comment]
@leios have you seen the feature requests for gitbook? https://gitbook.canny.io/feature-requests 

Also you may want to try talking to Aaron (cofounder) who is really active on their slack (public). Im not totally sure you ll be able to have an exception or something but i love this project and i don't see too many platforms it would work.

Hope it helps!

**Comment by leios** [comment]
Hey @MarcoPorracin . We added our feature requests at the time; however, it didn't seem like they were taken into consideration. I didn't consider checking the slack. Ultimately, I think we are fine with the tools we currently have (legacy gitbook, basically). Right now, we don't have enough political sway to really warrant any exceptions on gitbook's part, plus the migration away from the gitbook site has already occurred.

You are right that there aren't too many platforms that work for our purposes here, but we'll keep an eye out. If it ends up being that the new gitbook is better, we'll transition back to that.

I think it's about time we close this issue.

**Comment by julianschacher** [comment]
@MarcoPorracin And the new gitbook is also closed-source. So there’s that.
