### ISSUE TITLE
Euclidian algorithm  in lolcode doesn't run

### ISSUE THREAD

**Issue by ShadowMitia** [algorithm-archivists/algorithm-archive#917]
# Bug Report

## Description

I've tried running the lolcode code for the euclidian method example.

I'm getting `contents/euclidean_algorithm/code/lolcode/euclid.lol:27 variable does not exist: EI`

### Steps to Reproduce

Take the code and run it through an interpreter.

### Expected behavior
Should run with giving an error.

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by Fabus1184** [comment]
`EI` -> `I` and the algorithm works again. The tests are successful.

**Comment by ShadowMitia** [comment]
Well that was easy xD
@Fabus1184 Do you want to open a PR for it?

**Comment by Fabus1184** [comment]
yes
