### ISSUE TITLE
Split operator method and Cooley-Tukey in Rust don't compile.

### ISSUE THREAD

**Issue by PeanutbutterWarrior** [algorithm-archivists/algorithm-archive#944]
# Bug Report

## Description

Both split operator method and Cooley-Tukey don't compile in Rust. Only slight changes are needed as far as I can tell.

### Steps to Reproduce

Neither file has a Cargo.toml file which is required for dependencies. After creating a Cargo.toml for each with `num = "0.4.0"`, `rustfft = "5.1.1"`, and `rand = "0.8.4"` and running `cargo build` they fail with the errors in the screenshots

### Expected behavior

They should compile without errors.

## Screenshots

Cooley-tukey errors:
![image](https://user-images.githubusercontent.com/50717143/143773117-c3ae244a-27ef-4ed4-aa6a-1c27bd1c174a.png)

Split-Operator method errors:
![image](https://user-images.githubusercontent.com/50717143/143773131-38fea7ce-c195-4edd-87ad-97f11b8a168c.png)

## Environment

 - OS: Windows
 - OS Version: Windows 10 Home versiom 20H2 build 19042.1348
 - Cargo version: cargo 1.55.0 (32da73ab1 2021-08-23)

## For Algorithm Archive Developers

- [ ] The bug can be reproduced
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by Amaras** [comment]
What happens if you replace `rustfft::FFTPlanner` with `rustfft:FftPlanner`? It won't fix the Cooley-Tukey method, but that could help for the Split-op method

**Comment by PeanutbutterWarrior** [comment]
Solved by #945 . A previous version of the library was needed
