### ISSUE TITLE
MathJax stuff at the top of the chapters causes bad search result previews

### ISSUE THREAD

**Issue by julianschacherpp** [algorithm-archivists/algorithm-archive#97]
The MathJax stuff at the top of the individual chapters causes bad result previews when searching the AAA.

<img width="1764" alt="screen shot 2018-04-30 at 03 00 27_aaa_search" src="https://user-images.githubusercontent.com/26492670/39412889-18735958-4c23-11e8-9bbf-c4596db4ef99.png">

**Comment by leios** [comment]
Oh, let me try that. If that works, it solves a lot of other problems.

**Comment by leios** [comment]
This should be solved by this commit: https://github.com/algorithm-archivists/algorithm-archive/commit/3176e828f1d3315cf4eed05ce4a39d706af34736

(question: is there a way to tag commit messages like there is a way to tag issues and PR's?)

**Comment by julianschacherpp** [comment]
@leios well, I can click the commit hash to see the commit :)
The issue seems to be resolved. I close it now.
