### ISSUE TITLE
Suggestion: Add github CLI inside Docker

### ISSUE THREAD

**Issue by ShadowMitia** [algorithm-archivists/algorithm-archive#970]
I was thinking we could maybe add the [Github CLI tool](https://github.com/cli/cli/releases/tag/v2.3.0), not particular reason other than have it as a commodity for people using Docker.

It would make testing PRs a bit easier, because you can just go and grab the command directly from Github:

![image](https://user-images.githubusercontent.com/3752363/144751319-8586bac8-e4e1-4f29-9d44-38758a7c5722.png)

I don't really use the tool for anything else myself, but maybe there are other uses to simplify git/github interaction?

**Comment by Amaras** [comment]
I use the official CLI myself (outside of Docker containers), and I can tell you that it's way easier to switch between PRs.

However, if we modify the Docker configuration, it requires to build the image locally, and I don't think there is an extension to do that.

**Comment by ShadowMitia** [comment]
As pointed out by @Amaras on Discord, `gh` requires authentication/token to allow to be used correctly. Even with the `gh pr` one, which is annoying... Still could be useful, but much less practical right now.

**Comment by Amaras** [comment]
Closing this for now
